// Generated by https://quicktype.io

export interface GiphyResponse {
    data: Data;
    meta: Meta;
}

export interface Data {
    type:              string;
    id:                string;
    url:               string;
    slug:              string;
    bitly_gif_url:     string;
    bitly_url:         string;
    embed_url:         string;
    username:          string;
    source:            string;
    title:             string;
    rating:            string;
    content_url:       string;
    source_tld:        string;
    source_post_url:   string;
    is_sticker:        number;
    import_datetime:   string;
    trending_datetime: string;
    images:            Images;
    user:              User;
}

export interface Images {
    fixed_width_still:        The480_WStill;
    preview_gif:              The480_WStill;
    fixed_height_downsampled: { [key: string]: string };
    preview:                  DownsizedSmall;
    fixed_height_small:       { [key: string]: string };
    downsized:                The480_WStill;
    fixed_width_downsampled:  { [key: string]: string };
    fixed_width:              { [key: string]: string };
    downsized_still:          The480_WStill;
    downsized_medium:         The480_WStill;
    original_mp4:             DownsizedSmall;
    downsized_large:          The480_WStill;
    preview_webp:             The480_WStill;
    original:                 { [key: string]: string };
    original_still:           The480_WStill;
    fixed_height_small_still: The480_WStill;
    fixed_width_small:        { [key: string]: string };
    looping:                  { [key: string]: string };
    downsized_small:          DownsizedSmall;
    fixed_width_small_still:  The480_WStill;
    fixed_height_still:       The480_WStill;
    fixed_height:             { [key: string]: string };
    "480w_still":             The480_WStill;
}

export interface The480_WStill {
    url:    string;
    width:  string;
    height: string;
    size?:  string;
}

export interface DownsizedSmall {
    height:   string;
    mp4:      string;
    mp4_size: string;
    width:    string;
}

export interface User {
    avatar_url:    string;
    banner_image:  string;
    banner_url:    string;
    profile_url:   string;
    username:      string;
    display_name:  string;
    description:   string;
    is_verified:   boolean;
    website_url:   string;
    instagram_url: string;
}

export interface Meta {
    msg:         string;
    status:      number;
    response_id: string;
}
